"""
GitHub integration — creates repos and pushes spec files on PO approval.
"""

import os
import base64
import httpx
import logging
from typing import Optional

logger = logging.getLogger(__name__)
GITHUB_API_URL = "https://api.github.com"


class GitHubClient:
    def __init__(self, token: str | None = None):
        self.token = token or os.environ.get("GITHUB_TOKEN")
        if not self.token:
            logger.warning("[GitHub] No token configured. Set GITHUB_TOKEN to enable.")
        self.headers = {
            "Authorization": f"Bearer {self.token}" if self.token else "",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    async def get_authenticated_user(self) -> dict:
        if not self.token:
            logger.warning("[GitHub] No token — skipping auth check")
            return {"login": "unknown"}

        try:
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.get(f"{GITHUB_API_URL}/user", headers=self.headers)
                response.raise_for_status()
                return response.json()
        except Exception as e:
            logger.error(f"[GitHub] Auth check failed: {e}")
            return {"login": "unknown"}

    async def create_repo_and_push_spec(
        self,
        repo_name: str,
        spec_content: str,
        description: str = "",
        private: bool = False,
    ) -> str:
        """Create a GitHub repo and push the spec as SPEC.md. Returns the repo URL."""

        if not self.token:
            logger.warning("[GitHub] No token — cannot create repo")
            return "https://github.com/[requires-github-token]"

        try:
            user = await self.get_authenticated_user()
            username = user["login"]

            # Sanitize repo name
            repo_name = repo_name.lower().replace(" ", "-").replace("/", "-")[:100]

            # Create the repo
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.post(
                    f"{GITHUB_API_URL}/user/repos",
                    headers=self.headers,
                    json={
                        "name": repo_name,
                        "description": description[:255] if description else "",
                        "private": private,
                        "auto_init": True,
                    },
                )
                response.raise_for_status()
                repo_data = response.json()

            repo_url = repo_data["html_url"]
            logger.info(f"[GitHub] Created repo: {repo_url}")

            # Push SPEC.md
            encoded_content = base64.b64encode(spec_content.encode()).decode()
            async with httpx.AsyncClient(timeout=10) as client:
                await client.put(
                    f"{GITHUB_API_URL}/repos/{username}/{repo_name}/contents/SPEC.md",
                    headers=self.headers,
                    json={
                        "message": "feat: add Spectra-generated spec",
                        "content": encoded_content,
                    },
                )

            # Push README.md
            readme = f"# {repo_name}\n\nSpec generated by [Spectra](https://app.base44.com/superagent/69f19298360c8dc869b3fd9b).\n\nSee [SPEC.md](./SPEC.md) for the full specification.\n"
            encoded_readme = base64.b64encode(readme.encode()).decode()
            async with httpx.AsyncClient(timeout=10) as client:
                await client.put(
                    f"{GITHUB_API_URL}/repos/{username}/{repo_name}/contents/README.md",
                    headers=self.headers,
                    json={
                        "message": "docs: add README",
                        "content": encoded_readme,
                    },
                )

            logger.info(f"[GitHub] Pushed SPEC.md and README.md")
            return repo_url

        except Exception as e:
            logger.error(f"[GitHub] Repo creation failed: {e}")
            return "https://github.com/[creation-failed]"
